### PR TITLE
mirage-types.lwt -> mirage-types-lwt

### PR DESCRIPTION
**Pull request by yomimono**

### CODE REVIEW

**Comment by hannesm** [comment]
I don't understand the .5 breakage (where vchan is unhappy)... .3 and .4 should be fixed by https://github.com/mirage/mirage-dev/pull/261 and https://github.com/mirage/ocaml-dns/pull/113

**Comment by yomimono** [comment]
I can reproduce the vchan install failure locally; I'll get it sorted.

**Comment by yomimono** [comment]
.5 still broken, but the reason looks more serious:

```
# File "src/dog_listen.ml", line 98, characters 2-41:
# Error: Unbound value Irmin_unix.install_dir_polling_listener
# Command exited with code 2.
```

@samoht, maybe you know why?

**Comment by samoht** [comment]
`dog` is not supposed to work with irmin 0.12, I guess I forgot to fix that dependency

**Comment by yomimono** [comment]
@samoht is it OK to merge this, as without it the branch is more broken?

**Comment by avsm** [comment]
I'm going ahead and merging this to unblock things

**Comment by avsm** [comment]
PR to upper bound dog.0.2.1 in https://github.com/ocaml/opam-repository/pull/8115
